#!/bin/bash

# 🌾 ROTACIÓN GANADO - BIENVENIDA
# Magrotec - Gestión Ganadera Regenerativa Premium
# Version: 1.0.0 MVP
# Status: ✅ LISTO PARA USAR

echo ""
echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║                                                                    ║"
echo "║           🌾 ROTACIÓN GANADO - MAGROTEC v1.0.0 MVP 🌾            ║"
echo "║                                                                    ║"
echo "║    ¡Bienvenido a la plataforma premium de gestión ganadera!       ║"
echo "║                                                                    ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""

echo "📍 UBICACIÓN DEL PROYECTO:"
echo "   c:\Users\DanielVillamizar\GanaderiaRegenerativa"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 3 PASOS PARA EMPEZAR (5 MINUTOS)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "1️⃣  LEVANTA DOCKER:"
echo ""
echo "    $ cd c:\Users\DanielVillamizar\GanaderiaRegenerativa"
echo "    $ docker-compose up -d"
echo ""
echo "    (Esto inicia: PostgreSQL, API Backend, Web Frontend)"
echo "    Espera 30 segundos a que PostgreSQL esté listo..."
echo ""

echo "2️⃣  PREPARA LA BASE DE DATOS:"
echo ""
echo "    $ docker-compose exec api npm run db:push"
echo "    $ docker-compose exec api npm run db:seed"
echo ""
echo "    (Esto crea las tablas y carga datos de ejemplo)"
echo "    • 1 finca: Las Praderas (50 ha)"
echo "    • 8 potreros"
echo "    • 15 animales"
echo "    • 5 pesajes históricos"
echo ""

echo "3️⃣  ABRE EN TU NAVEGADOR:"
echo ""
echo "    🌐 Frontend:  http://localhost:3001"
echo "    📡 API:       http://localhost:3000/api/v1"
echo "    📚 Docs:      http://localhost:3000/api/docs"
echo ""
echo "    Login con:"
echo "    📧 admin@magrotec.com"
echo "    🔑 Admin123!"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📚 DOCUMENTACIÓN (Recomendado leer en este orden)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "1. OVERVIEW (2 minutos):"
echo "   📖 README.md o LEEME.md"
echo "   └─ Qué es, por qué, cómo empezar"
echo ""

echo "2. TOUR (5 minutos):"
echo "   📖 EXECUTIVE_SUMMARY.md"
echo "   └─ Estadísticas: 8 módulos, 35 endpoints, 6 gráficas"
echo ""

echo "3. ARQUITECTURA (15 minutos):"
echo "   📖 docs/arquitectura.md"
echo "   └─ Por qué JWT, Prisma, Next.js, TailwindCSS, etc."
echo ""

echo "4. RÁPIDA REFERENCIA (10 minutos):"
echo "   📖 docs/guia_rapida.md"
echo "   └─ Comandos, debugging, agregar features"
echo ""

echo "5. PROFUNDIDAD (Por tema):"
echo "   📖 docs/modelo_datos.md      → 15 tablas de BD"
echo "   📖 docs/calculos.md          → UA, ganancia, demanda"
echo "   📖 docs/decisiones.md        → Decisiones de diseño"
echo "   📖 docs/CONTRIBUTING.md      → Estándares de código"
echo ""

echo "6. ÍNDICE MAESTRO:"
echo "   📖 INDEX.md"
echo "   └─ Navegar por toda la documentación"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⚡ COMANDOS FRECUENTES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "🛠️  DESARROLLO:"
echo "    $ npm run dev              # Levantar todas las apps"
echo "    $ npm run lint             # Validar código"
echo "    $ npm run format           # Formatear código"
echo "    $ npm run build            # Compilar"
echo ""

echo "🔧 BACKEND (apps/api/):"
echo "    $ npm run dev              # Watch mode"
echo "    $ npx prisma studio       # Ver BD visualmente"
echo "    $ npm run test            # Unit tests"
echo ""

echo "🎨 FRONTEND (apps/web/):"
echo "    $ npm run dev             # Dev server (hot reload)"
echo "    $ npm run build           # Build optimizado"
echo "    $ npm run test            # Tests"
echo ""

echo "🐳 DOCKER:"
echo "    $ docker-compose up -d    # Levantar"
echo "    $ docker-compose logs -f  # Ver logs"
echo "    $ docker-compose down     # Apagar"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✨ CARACTERÍSTICAS INCLUIDAS (MVP)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "✅ AUTENTICACIÓN:"
echo "   • JWT login/logout"
echo "   • 4 roles: ADMIN, TECHNICIAN, MANAGER, VIEWER"
echo "   • Control de acceso por finca"
echo "   • Auditoría de cambios"
echo ""

echo "✅ GESTIÓN DE GANADERÍA:"
echo "   • Fincas (CRUD)"
echo "   • Potreros (CRUD)"
echo "   • Lotes & Animales (CRUD)"
echo "   • Pesajes con histórico"
echo "   • Movimientos (rotación entrada/salida)"
echo "   • Aforos (marcos cuadrados)"
echo ""

echo "✅ CÁLCULOS AUTOMÁTICOS:"
echo "   • UA = Peso / 450"
echo "   • Ganancia = Peso Final - Inicial"
echo "   • Demanda = UA × 2.5%"
echo "   • Días recomendados = Forraje / Demanda"
echo ""

echo "✅ DASHBOARD CON 6 GRÁFICAS:"
echo "   • Evolución de peso"
echo "   • Evolución de UA"
echo "   • Ocupación de potreros"
echo "   • Forraje disponible"
echo "   • KPIs de resumen"
echo "   • Alertas operativas"
echo ""

echo "✅ SEGURIDAD:"
echo "   • JWT con expiración"
echo "   • Hashing bcryptjs"
echo "   • RBAC completo"
echo "   • Soft deletes"
echo "   • CORS configurado"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 STACK TECNOLÓGICO"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "Backend:   NestJS + TypeScript + Prisma + PostgreSQL"
echo "Frontend:  Next.js 14 + React 18 + TailwindCSS + React Query"
echo "DevOps:    Docker + GitHub Actions + Husky + Turbo"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🗺️  PRÓXIMAS FASES (ROADMAP)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "Fase 2 (Q1 2024):"
echo "  ☐ Tests unitarios & E2E"
echo "  ☐ Formularios crear/editar"
echo "  ☐ Planificador Gantt de rotación"
echo "  ☐ Export PDF/Excel"
echo "  ☐ Entra ID / Azure AD B2C"
echo "  ☐ Notificaciones"
echo ""

echo "Fase 3 (Q2 2024):"
echo "  ☐ App móvil (React Native)"
echo "  ☐ IoT sensores"
echo "  ☐ Machine Learning"
echo "  ☐ Multi-idioma"
echo "  ☐ Dark mode"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "❓ FAQ RÁPIDO"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "P: ¿Qué es Rotación Ganado?"
echo "R: Sistema web para gestionar ganadería regenerativa con rotación"
echo "   de potreros. Calcula automáticamente UA, ganancia y fornaje."
echo ""

echo "P: ¿Qué es una Unidad Animal (UA)?"
echo "R: Medida estándar de biomasa = 450 kg"
echo "   Ejemplo: 4500 kg / 450 = 10 UA"
echo ""

echo "P: ¿Por qué Docker?"
echo "R: Para que todo corra igual en tu laptop que en producción."
echo "   Evita 'funciona en mi máquina' problems."
echo ""

echo "P: ¿Cuántos endpoints tiene?"
echo "R: 35+ endpoints REST"
echo "   Ver documentación en http://localhost:3000/api/docs"
echo ""

echo "P: ¿Cuántas gráficas tiene el dashboard?"
echo "R: 6 gráficas principales + KPIs + Alertas"
echo ""

echo "P: ¿Qué debo cambiar antes de producción?"
echo "R: En apps/api/.env:"
echo "   - DATABASE_URL (tu PostgreSQL)"
echo "   - JWT_SECRET (nueva clave secreta)"
echo "   - CORS_ORIGIN (tu dominio frontend)"
echo ""

echo "P: ¿Dónde está la documentación?"
echo "R: Comienza con README.md o INDEX.md"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🆘 TROUBLESHOOTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "Error: Puerto 3000 ya está en uso"
echo "Solución: Cambiar en docker-compose.yml o"
echo "          lsof -i :3000 para ver qué lo ocupa"
echo ""

echo "Error: BD no syncroniza"
echo "Solución: cd apps/api && npx prisma migrate reset"
echo ""

echo "Error: Token expirado"
echo "Solución: Limpiar localStorage en browser y re-login"
echo ""

echo "Error: node_modules muy grande"
echo "Solución: npm install --legacy-peer-deps"
echo ""

echo "Ver documentación completa en: docs/guia_rapida.md"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎉 ¡LISTO PARA EMPEZAR!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "PRÓXIMOS PASOS:"
echo ""
echo "  1. Lee README.md (5 min)"
echo "  2. Ejecuta: docker-compose up -d (espera 30s)"
echo "  3. Ejecuta: docker-compose exec api npm run db:seed"
echo "  4. Abre: http://localhost:3001"
echo "  5. Login: admin@magrotec.com / Admin123!"
echo "  6. Explora el dashboard 📊"
echo "  7. Lee docs/arquitectura.md para entender decisiones"
echo ""

echo "INFORMACIÓN:"
echo "  📁 Proyecto: c:\Users\DanielVillamizar\GanaderiaRegenerativa"
echo "  📖 Documentación: /docs (6 archivos)"
echo "  🐳 Docker: docker-compose up -d"
echo "  🌐 Frontend: http://localhost:3001"
echo "  📡 API: http://localhost:3000/api/v1"
echo ""

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║                                                                    ║"
echo "║          ¡Bienvenido al futuro de la ganadería! 🌾🐄              ║"
echo "║                                                                    ║"
echo "║             Rotación Ganado - Magrotec v1.0.0 MVP                ║"
echo "║                          Status: ✅ LISTO                         ║"
echo "║                                                                    ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""
